#!/global/common/software/m3408/python/3.7/bin/python

import os
import sys
from slack import WebClient
from slack.errors import SlackApiError

with open(os.path.join(os.environ.get("HOME"), ".slack_tok")) as f:
        tok = f.read()
client = WebClient(token=tok)

text = sys.argv[1]

try:
    response = client.chat_postMessage(
        channel='#workflow_jobs',
        text=text)
    assert response["message"]["text"] == text
except SlackApiError as e:
    # You will get a SlackApiError if "ok" is False
    assert e.response["ok"] is False
    assert e.response["error"]  # str like 'invalid_auth', 'channel_not_found'
    print(f"Got an error: {e.response['error']}")

