# This isn't used yet.
Global:
        cromwell_url: http://cori21-ib0:8088
        template_dir: global/cfs/cdirs/m3408/aim2/tools
        wdl_dir: global/cfs/cdirs/m3408/aim2/dev/wdl/
        data_dir: global/cfs/cdirs/m3408/ficus/pipeline_products
        jamo_dir: global/cfs/cdirs/m3408/ficus/jamo
        # Raw data space
        # This needs to be public so data can be fetch via http
        raw_dir: global/cfs/cdirs/m3408/ficus/pipeline_products/raw
        agent_state: global/cfs/cdirs/m3408/ficus/agent.state
        # Watch List
        watch_list: global/cfs/cdirs/m3408/ficus/pipeline_products/watch.lst
        # Staging area for Cromwell
        stage_dir: global/cscratch1/sd/nmdcda/drop
        resource: NERSC-Cori
        url_root: https://data.microbiomedata.org/data/

Product Mappings:
         'Metagenome Metatranscriptome': 'Metatranscriptome'
         'Metagenome Minimal Draft': 'Metagenome'
         'Metagenome Standard Draft': 'Metagenome'

Object Type Mappings:
        Metagenome: metagenome_raw_paired_end_reads
        Metatranscriptome: metatranscriptome_raw_paired_end_reads

Metagenome:
        version: "1.0.6"
        pipeline: "metag_annotation"
        prefix: mga0
        git_url: "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1"
        wdl: /global/cfs/cdirs/m3408/aim2/dev/wdl/nmdc-metag_full.wdl
        bundle: /global/cfs/cdirs/m3408/aim2/dev/wdl/bundle-2022-03-02.zip
        inputs:
          nmdc_metag.proj: "{actid}"
          nmdc_metag.informed_by: "{informed_by}"
          nmdc_metag.input_file: "{inputfile}"
          nmdc_metag.git_url: "{git_url}"
          nmdc_metag.outdir: "{data_dir}/{actid}"
          nmdc_metag.resource: "{resource}"
          nmdc_metag.url_root: "https://data.microbiomedata.org/data/"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "{opid}"
          activity_id: "{actid}"

SingleEndMetagenome:
        version: "1.0.6"
        pipeline: "metag_annotation"
        prefix: mga0
        git_url: "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1"
        wdl: /global/cfs/cdirs/m3408/aim2/dev/metaG/single_end/nmdc-metag_full_SE.wdl
        bundle: /global/cfs/cdirs/m3408/aim2/dev/metaG/single_end/bundle.zip
        inputs:
          nmdc_metag.proj: "{actid}"
          nmdc_metag.informed_by: "{informed_by}"
          nmdc_metag.input_file: "{inputfile}"
          nmdc_metag.git_url: "{git_url}"
          nmdc_metag.outdir: "{data_dir}/{actid}"
          nmdc_metag.resource: "{resource}"
          nmdc_metag.url_root: "https://data.microbiomedata.org/data/"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "{opid}"
          activity_id: "{actid}"

Metatranscriptome:
        version: "1.0.2"
        pipeline: "metat_annotation"
        prefix: mta0
        git_url: "https://github.com/microbiomedata/metaT"
        wdl: /global/cfs/cdirs/m3408/aim2/dev/metaT/wdls/metaT.wdl
        bundle: /global/cfs/cdirs/m3408/aim2/dev/metaT/wdls/bundle-2022-04-12.zip
        inputs:
          nmdc_metat.proj: "{actid}"
          nmdc_metat.informed_by: "{informed_by}"
          nmdc_metat.input_file: "{inputfile}"
          nmdc_metat.git_url: "{git_url}"
          nmdc_metat.outdir: "{data_dir}/{actid}"
          nmdc_metat.resource: "{resource}"
          nmdc_metat.url_root: "https://data.microbiomedata.org/data/"
          nmdc_metat.metat_folder: "/global/cfs/cdirs/m3408/aim2/metatranscriptomics/metaT"
          nmdc_metat.database: "/refdata"
          nmdc_metat.activity_id: "{informed_by}"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "{opid}"
          activity_id: "{actid}"

UpdateMetagenome:
        version: "1.0.6"
        pipeline: "metag_update"
        prefix: mga0
        git_url: "https://github.com/microbiomedata/metaG/releases/tag/0.1"
        wdl: /global/cfs/cdirs/m3408/aim2/dev/wdl/nmdc-metag_full.wdl.mags
        bundle: /global/cfs/cdirs/m3408/aim2/dev/wdl/bundle-2022-04-25.zip
        inputs:
          nmdc_metag.proj: "{actid}"
          nmdc_metag.informed_by: "{informed_by}"
          nmdc_metag.input_file: "{inputfile}"
          nmdc_metag.git_url: "{git_url}"
          nmdc_metag.outdir: "{data_dir}/{actid}"
          nmdc_metag.resource: "{resource}"
          nmdc_metag.url_root: "https://data.microbiomedata.org/data/"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "na"
          activity_id: "{actid}"

ReannotateMetagenome:
        version: "1.0.6"
        pipeline: "metag_reanno"
        prefix: mga0
        git_url: "https://github.com/microbiomedata/metaG/releases/tag/0.1"
        wdl: /global/cfs/cdirs/m3408/aim2/dev/wdl/nmdc-metag-reannotate.wdl
        bundle: /global/cfs/cdirs/m3408/aim2/dev/wdl/bundle-reanno.zip
        inputs:
          nmdc_metag_reanno.proj: "{actid}"
          nmdc_metag_reanno.orig_prefix: "{orig_prefix}"
          nmdc_metag_reanno.prev_dir: "{data_dir}/{orig_prefix}"
          nmdc_metag_reanno.input_file: "{jamo_dir}/{inputfile}"
          nmdc_metag_reanno.git_url: "{git_url}"
          nmdc_metag_reanno.outdir: "{data_dir}/{actid}"
          nmdc_metag_reanno.informed_by: "{informed_by}"
          nmdc_metag_reanno.resource: "{resource}"
          nmdc_metag_reanno.url_root: "https://data.microbiomedata.org/data/"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "na"
          activity_id: "{actid}"

Metagenome-1.0.5.1:
        version: "1.0.5.1"
        pipeline: "metag_annotation"
        prefix: mga0
        git_url: "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1"
        wdl:    /global/cfs/cdirs/m3408/aim2/wdl-snapshots/nmdc-metag-full-1.0.5.1.wdl
        bundle: /global/cfs/cdirs/m3408/aim2/wdl-snapshots/bundle-1.0.5.1.zip
        inputs:
          nmdc_metag.proj: "{actid}"
          nmdc_metag.informed_by: "{informed_by}"
          nmdc_metag.input_file: "{inputfile}"
          nmdc_metag.git_url: "{git_url}"
          nmdc_metag.outdir: "{data_dir}/{actid}"
          nmdc_metag.resource: "{resource}"
          nmdc_metag.url_root: "https://data.microbiomedata.org/data/"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "{opid}"
          activity_id: "{actid}"
          study: "{study}"

Metagnome-JGI-1.0.6.0:
        version: "1.0.6.0"
        pipeline: "metag_jgi"
        prefix: mga0
        git_url: "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1"
        wdl:    /global/cfs/cdirs/m3408/aim2/dev/wdl/nmdc-metag-jgi.wdl
        bundle: /global/cfs/cdirs/m3408/aim2/dev/wdl/bundle-jgi.zip
        inputs:
          nmdc_metag_jgi.proj: "{actid}"
          nmdc_metag_jgi.gold_id: "{gold_id}"
          nmdc_metag_jgi.informed_by: "{informed_by}"
          nmdc_metag_jgi.jdir: "{jdir}"
          nmdc_metag_jgi.git_url: "{git_url}"
          nmdc_metag_jgi.outdir: "{data_dir}/{actid}"
          nmdc_metag_jgi.resource: "{resource}"
          nmdc_metag_jgi.url_root: "https://data.microbiomedata.org/data/"
        labels:
          pipeline_version: "{version}"
          pipeline: "{pipeline}"
          project_id: "{informed_by}"
          submitter: "{user}"
          opid: "{opid}"
          activity_id: "{actid}"
          study: "{study}"

